### ISSUE TITLE
[BUG] Head stacking issue - Tracking progress

### ISSUE THREAD

**Issue by Thatsmusic99** [Thatsmusic99/HeadsPlus#11]
## Information
This is a self-opened issue to help me keep track of one of the biggest issues in the plugin, of which is heads not stacking after restarts.

Issue combatted for: 

- [x] Mob drops with owners
- [x] Mob drops with custom textures
- [x] Crafting with owners
- [x] Crafting with custom textures
- [ ] Heads retreived from /myhead and /head
- [x] Heads retreived from /heads

### System environment
- Server version: 1.14.4
- HeadsPlus version: v6.5.4
- Whether or not the plugin uses MySQL: false
- Server type (e.g Spigot, Paper): Spigot
- Uses Vault: true
- Any other pieces of information that may be required: Java 11

**Comment by Thatsmusic99** [comment]
It's super likely that this issue may not be fixable after looking closer at it. For context, here's a small overview as to why:

- When using players to create mob skulls, there is a specific method that is used. (SkullMeta#setOwner(String ownerName) or SkullMeta#setOwner(OfflinePlayer player))
- Unlike custom textures, it creates all the parameters for the texture value itself.
- Inside of a player's skin texture value, the decoded contents look like this: {"timestamp":1564210865613,"profileId":"7091cdbcebdc4eaca6b225dd8acd3a0e","profileName":"Thatsmusic99","signatureRequired":true,"textures":{"SKIN":{"url":"http://textures.minecraft.net/texture/55d0287db2ea512dbadae1ba070a0d3f7eb9862d732ca89a1516c4f0f9c940ea","metadata":{"model":"slim"}}}}
- The timestamp is used to check when the skin was last retrieved, which is different every server restart. 
- This therefore stops heads from stacking.

Best I can do is make a temporary workaround so that all mob heads use custom textures..

**Comment by Thatsmusic99** [comment]
Deemed unsolvable as of currently and not a major issue, but has instead been provided with a workaround; closing this for the time being.
