### ISSUE TITLE
Feature Tracker: HeadsPlus

### ISSUE THREAD

**Issue by Thatsmusic99** [Thatsmusic99/HeadsPlus#17]
As I get busier and busier, it's harder to keep track of stuff I want to sort out/add, so I'll leave it here for you all to see.

- [x] Redo locale system
- [x] Add XP modify command
- [ ] Leaderboard in XP 
- [ ] Attempt to make as much of the GUIs "interactive"
  - E.g. for configuration in-game, enabling and disabling options just using clicks, storing all changes in a log file
- [ ] ~~Add head "bundles"~~ moving to HPC, people are obviously going to abuse it as a free resource
- [ ] Clean up the debug command
- [ ] Add more debugging to events
- [ ] Maybe create a different config for debugging?
- [x] Improve locale for other config files
- [ ] Finish the damn wiki
- [ ] Allow challenge tracking, so players can "pin" challenges and filter out ones they have/haven't done
- [ ] Add [HBuy] (buy from /heads through just a sign) and [HSell] signs
- [ ] Maybe a "head history" feature.

Feel free to suggest anything below or in a separate report.

**Comment by Thatsmusic99** [comment]
Replaced with the todo on Discord
